### ISSUE TITLE
Hook the constructor.

### ISSUE THREAD

**Issue by melonaerial** [idanr1986/droidmon#3]
Hello. Can i hook the constructor of object with your hooks.json file ? What is API for that ?

**Comment by idanr1986** [comment]
yes you can just leave the method empty , you can find example in the json

**Comment by melonaerial** [comment]
```
        {
            "class_name": "java.net.URI", 
            "method": "<init>", 
            "thisObject": false, 
            "type": "fingerprint"
        },
        {
            "class_name": "java.net.URI", 
            "method": "", 
            "thisObject": false, 
            "type": "fingerprint"
        }
```

I've tried to make hook this way, but it not works for me.

**Comment by melonaerial** [comment]
```
W/System.err( 5631): java.net.UnknownHostException: Unable to resolve host "lgfvfghcbyd.xyz": No address associated with hostname
W/System.err( 5631):    at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
W/System.err( 5631):    at java.net.InetAddress.lookupHostByName(Native Method)
W/System.err( 5631):    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
W/System.err( 5631):    at java.net.InetAddress.getAllByName(InetAddress.java:214)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
W/System.err( 5631):    at java.net.InetAddress.getAllByName(Native Method)
W/System.err( 5631):    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
W/System.err( 5631):    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(Native Method)
W/System.err( 5631):    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/System.err( 5631):    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/System.err( 5631):    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
W/System.err( 5631):    at org.apache.http.impl.client.DefaultRequestDirector.execute(Native Method)
W/System.err( 5631):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
W/System.err( 5631):    at org.apache.http.impl.client.AbstractHttpClient.execute(Native Method)
W/System.err( 5631):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
W/System.err( 5631):    at org.apache.http.impl.client.AbstractHttpClient.execute(Native Method)
W/System.err( 5631):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err( 5631):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
W/System.err( 5631):    at org.apache.http.impl.client.AbstractHttpClient.execute(Native Method)
```

And have found this. It looks like if in some code will be exception, then all logs from DroidMon will be missed, cause i don't see log messages from this methods in logcat.

**Comment by idanr1986** [comment]
{
            "class_name": "javax.crypto.spec.SecretKeySpec", 
            "method": null, 
            "thisObject": false, 
            "type": "crypto"
        },
